set(EXTERNAL_PROJECT_MODULES_DIR "${LITERTLM_MODULES_DIR}/external")

include(${LITERT_RECIPES_DIR}/opencl/opencl.cmake)
include(${LITERT_RECIPES_DIR}/absl/absl.cmake)
include(${LITERT_RECIPES_DIR}/protobuf/protobuf.cmake)
include(${LITERT_RECIPES_DIR}/flatbuffers/flatbuffers.cmake)
include(${LITERT_RECIPES_DIR}/gtest/gtest.cmake)
include(${LITERT_RECIPES_DIR}/sentencepiece/sentencepiece.cmake)
include(${LITERT_RECIPES_DIR}/tokenizers/tokenizers.cmake)
include(${LITERT_RECIPES_DIR}/re2/re2.cmake)
include(${LITERT_RECIPES_DIR}/tflite/tflite.cmake)
include(${LITERT_RECIPES_DIR}/litert/litert.cmake)